name = "Niivue"
uuid = "ffb98d2b-b27a-4f95-a5bd-69d337ba623a"
authors = ["Korbinian Eckstein korbinian90@gmail.com"]
version = "1.0.0-DEV"

[deps]
Bonito = "824d6782-a2ef-11e9-3a09-e5662e0c26f8"

[compat]
Bonito = "4.0.3"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
